name: Test
on:
  push:
jobs:
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 16
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines --ignore-scripts
      - name: build
        run: yarn build
      - name: Run unit tests
        run: yarn test
        env:
          FORCE_COLOR: 2
